//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Seller.ProductDetailsReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_pathField;
        
        private double discountField;
        
        private double ratingField;
        
        private int ratingCountField;
        
        private int order_countField;
        
        private int quantity_availableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subcategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string image_path {
            get {
                return this.image_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.image_pathField, value) != true)) {
                    this.image_pathField = value;
                    this.RaisePropertyChanged("image_path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ratingCount {
            get {
                return this.ratingCountField;
            }
            set {
                if ((this.ratingCountField.Equals(value) != true)) {
                    this.ratingCountField = value;
                    this.RaisePropertyChanged("ratingCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int order_count {
            get {
                return this.order_countField;
            }
            set {
                if ((this.order_countField.Equals(value) != true)) {
                    this.order_countField = value;
                    this.RaisePropertyChanged("order_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int quantity_available {
            get {
                return this.quantity_availableField;
            }
            set {
                if ((this.quantity_availableField.Equals(value) != true)) {
                    this.quantity_availableField = value;
                    this.RaisePropertyChanged("quantity_available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string subcategory {
            get {
                return this.subcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.subcategoryField, value) != true)) {
                    this.subcategoryField = value;
                    this.RaisePropertyChanged("subcategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", ConfigurationName="ProductDetailsReference.ProductViewSoap")]
    public interface ProductViewSoap {
        
        // CODEGEN: Generating message contract since element name getItemResult from namespace http://localhost/ServiceBuyGrandSeller/ProductView.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/getItem", ReplyAction="*")]
        Order_Application_Seller.ProductDetailsReference.getItemResponse getItem(Order_Application_Seller.ProductDetailsReference.getItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/getItem", ReplyAction="*")]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.getItemResponse> getItemAsync(Order_Application_Seller.ProductDetailsReference.getItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/addRating", ReplyAction="*")]
        int addRating(int id, int rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/addRating", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addRatingAsync(int id, int rating);
        
        // CODEGEN: Generating message contract since element name username from namespace http://localhost/ServiceBuyGrandSeller/ProductView.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/loggedInUser", ReplyAction="*")]
        Order_Application_Seller.ProductDetailsReference.loggedInUserResponse loggedInUser(Order_Application_Seller.ProductDetailsReference.loggedInUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/loggedInUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.loggedInUserResponse> loggedInUserAsync(Order_Application_Seller.ProductDetailsReference.loggedInUserRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://localhost/ServiceBuyGrandSeller/ProductView.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/editProductDetail", ReplyAction="*")]
        Order_Application_Seller.ProductDetailsReference.editProductDetailResponse editProductDetail(Order_Application_Seller.ProductDetailsReference.editProductDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/editProductDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.editProductDetailResponse> editProductDetailAsync(Order_Application_Seller.ProductDetailsReference.editProductDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/deleteProduct", ReplyAction="*")]
        int deleteProduct(int productVal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/deleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<int> deleteProductAsync(int productVal);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItem", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.getItemRequestBody Body;
        
        public getItemRequest() {
        }
        
        public getItemRequest(Order_Application_Seller.ProductDetailsReference.getItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class getItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getItemRequestBody() {
        }
        
        public getItemRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemResponse", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.getItemResponseBody Body;
        
        public getItemResponse() {
        }
        
        public getItemResponse(Order_Application_Seller.ProductDetailsReference.getItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class getItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Order_Application_Seller.ProductDetailsReference.Item getItemResult;
        
        public getItemResponseBody() {
        }
        
        public getItemResponseBody(Order_Application_Seller.ProductDetailsReference.Item getItemResult) {
            this.getItemResult = getItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggedInUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loggedInUser", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.loggedInUserRequestBody Body;
        
        public loggedInUserRequest() {
        }
        
        public loggedInUserRequest(Order_Application_Seller.ProductDetailsReference.loggedInUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class loggedInUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        public loggedInUserRequestBody() {
        }
        
        public loggedInUserRequestBody(int id, string username) {
            this.id = id;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggedInUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loggedInUserResponse", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.loggedInUserResponseBody Body;
        
        public loggedInUserResponse() {
        }
        
        public loggedInUserResponse(Order_Application_Seller.ProductDetailsReference.loggedInUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class loggedInUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int loggedInUserResult;
        
        public loggedInUserResponseBody() {
        }
        
        public loggedInUserResponseBody(int loggedInUserResult) {
            this.loggedInUserResult = loggedInUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editProductDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editProductDetail", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.editProductDetailRequestBody Body;
        
        public editProductDetailRequest() {
        }
        
        public editProductDetailRequest(Order_Application_Seller.ProductDetailsReference.editProductDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class editProductDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productVal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subcategory;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double discount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string filePath;
        
        public editProductDetailRequestBody() {
        }
        
        public editProductDetailRequestBody(int productVal, string category, string subcategory, string name, string description, double price, double discount, int quantity, string filePath) {
            this.productVal = productVal;
            this.category = category;
            this.subcategory = subcategory;
            this.name = name;
            this.description = description;
            this.price = price;
            this.discount = discount;
            this.quantity = quantity;
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editProductDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editProductDetailResponse", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.editProductDetailResponseBody Body;
        
        public editProductDetailResponse() {
        }
        
        public editProductDetailResponse(Order_Application_Seller.ProductDetailsReference.editProductDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class editProductDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int editProductDetailResult;
        
        public editProductDetailResponseBody() {
        }
        
        public editProductDetailResponseBody(int editProductDetailResult) {
            this.editProductDetailResult = editProductDetailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductViewSoapChannel : Order_Application_Seller.ProductDetailsReference.ProductViewSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductViewSoapClient : System.ServiceModel.ClientBase<Order_Application_Seller.ProductDetailsReference.ProductViewSoap>, Order_Application_Seller.ProductDetailsReference.ProductViewSoap {
        
        public ProductViewSoapClient() {
        }
        
        public ProductViewSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductViewSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductViewSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductViewSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Order_Application_Seller.ProductDetailsReference.getItemResponse Order_Application_Seller.ProductDetailsReference.ProductViewSoap.getItem(Order_Application_Seller.ProductDetailsReference.getItemRequest request) {
            return base.Channel.getItem(request);
        }
        
        public Order_Application_Seller.ProductDetailsReference.Item getItem(int id) {
            Order_Application_Seller.ProductDetailsReference.getItemRequest inValue = new Order_Application_Seller.ProductDetailsReference.getItemRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.getItemRequestBody();
            inValue.Body.id = id;
            Order_Application_Seller.ProductDetailsReference.getItemResponse retVal = ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).getItem(inValue);
            return retVal.Body.getItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.getItemResponse> Order_Application_Seller.ProductDetailsReference.ProductViewSoap.getItemAsync(Order_Application_Seller.ProductDetailsReference.getItemRequest request) {
            return base.Channel.getItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.getItemResponse> getItemAsync(int id) {
            Order_Application_Seller.ProductDetailsReference.getItemRequest inValue = new Order_Application_Seller.ProductDetailsReference.getItemRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.getItemRequestBody();
            inValue.Body.id = id;
            return ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).getItemAsync(inValue);
        }
        
        public int addRating(int id, int rating) {
            return base.Channel.addRating(id, rating);
        }
        
        public System.Threading.Tasks.Task<int> addRatingAsync(int id, int rating) {
            return base.Channel.addRatingAsync(id, rating);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Order_Application_Seller.ProductDetailsReference.loggedInUserResponse Order_Application_Seller.ProductDetailsReference.ProductViewSoap.loggedInUser(Order_Application_Seller.ProductDetailsReference.loggedInUserRequest request) {
            return base.Channel.loggedInUser(request);
        }
        
        public int loggedInUser(int id, string username) {
            Order_Application_Seller.ProductDetailsReference.loggedInUserRequest inValue = new Order_Application_Seller.ProductDetailsReference.loggedInUserRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.loggedInUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            Order_Application_Seller.ProductDetailsReference.loggedInUserResponse retVal = ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).loggedInUser(inValue);
            return retVal.Body.loggedInUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.loggedInUserResponse> Order_Application_Seller.ProductDetailsReference.ProductViewSoap.loggedInUserAsync(Order_Application_Seller.ProductDetailsReference.loggedInUserRequest request) {
            return base.Channel.loggedInUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.loggedInUserResponse> loggedInUserAsync(int id, string username) {
            Order_Application_Seller.ProductDetailsReference.loggedInUserRequest inValue = new Order_Application_Seller.ProductDetailsReference.loggedInUserRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.loggedInUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            return ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).loggedInUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Order_Application_Seller.ProductDetailsReference.editProductDetailResponse Order_Application_Seller.ProductDetailsReference.ProductViewSoap.editProductDetail(Order_Application_Seller.ProductDetailsReference.editProductDetailRequest request) {
            return base.Channel.editProductDetail(request);
        }
        
        public int editProductDetail(int productVal, string category, string subcategory, string name, string description, double price, double discount, int quantity, string filePath) {
            Order_Application_Seller.ProductDetailsReference.editProductDetailRequest inValue = new Order_Application_Seller.ProductDetailsReference.editProductDetailRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.editProductDetailRequestBody();
            inValue.Body.productVal = productVal;
            inValue.Body.category = category;
            inValue.Body.subcategory = subcategory;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.quantity = quantity;
            inValue.Body.filePath = filePath;
            Order_Application_Seller.ProductDetailsReference.editProductDetailResponse retVal = ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).editProductDetail(inValue);
            return retVal.Body.editProductDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.editProductDetailResponse> Order_Application_Seller.ProductDetailsReference.ProductViewSoap.editProductDetailAsync(Order_Application_Seller.ProductDetailsReference.editProductDetailRequest request) {
            return base.Channel.editProductDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.editProductDetailResponse> editProductDetailAsync(int productVal, string category, string subcategory, string name, string description, double price, double discount, int quantity, string filePath) {
            Order_Application_Seller.ProductDetailsReference.editProductDetailRequest inValue = new Order_Application_Seller.ProductDetailsReference.editProductDetailRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.editProductDetailRequestBody();
            inValue.Body.productVal = productVal;
            inValue.Body.category = category;
            inValue.Body.subcategory = subcategory;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.quantity = quantity;
            inValue.Body.filePath = filePath;
            return ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).editProductDetailAsync(inValue);
        }
        
        public int deleteProduct(int productVal) {
            return base.Channel.deleteProduct(productVal);
        }
        
        public System.Threading.Tasks.Task<int> deleteProductAsync(int productVal) {
            return base.Channel.deleteProductAsync(productVal);
        }
    }
}
