//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Seller.ProductDetailsReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_pathField;
        
        private double discountField;
        
        private double ratingField;
        
        private int ratingCountField;
        
        private int order_countField;
        
        private int quantity_availableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subcategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string image_path {
            get {
                return this.image_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.image_pathField, value) != true)) {
                    this.image_pathField = value;
                    this.RaisePropertyChanged("image_path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ratingCount {
            get {
                return this.ratingCountField;
            }
            set {
                if ((this.ratingCountField.Equals(value) != true)) {
                    this.ratingCountField = value;
                    this.RaisePropertyChanged("ratingCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int order_count {
            get {
                return this.order_countField;
            }
            set {
                if ((this.order_countField.Equals(value) != true)) {
                    this.order_countField = value;
                    this.RaisePropertyChanged("order_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int quantity_available {
            get {
                return this.quantity_availableField;
            }
            set {
                if ((this.quantity_availableField.Equals(value) != true)) {
                    this.quantity_availableField = value;
                    this.RaisePropertyChanged("quantity_available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string subcategory {
            get {
                return this.subcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.subcategoryField, value) != true)) {
                    this.subcategoryField = value;
                    this.RaisePropertyChanged("subcategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", ConfigurationName="ProductDetailsReference.ProductViewSoap")]
    public interface ProductViewSoap {
        
        // CODEGEN: Generating message contract since element name getItemResult from namespace http://localhost/ServiceBuyGrandSeller/ProductView.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/getItem", ReplyAction="*")]
        Order_Application_Seller.ProductDetailsReference.getItemResponse getItem(Order_Application_Seller.ProductDetailsReference.getItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/getItem", ReplyAction="*")]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.getItemResponse> getItemAsync(Order_Application_Seller.ProductDetailsReference.getItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/addRating", ReplyAction="*")]
        int addRating(int id, int rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/addRating", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addRatingAsync(int id, int rating);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItem", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.getItemRequestBody Body;
        
        public getItemRequest() {
        }
        
        public getItemRequest(Order_Application_Seller.ProductDetailsReference.getItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class getItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getItemRequestBody() {
        }
        
        public getItemRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemResponse", Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/", Order=0)]
        public Order_Application_Seller.ProductDetailsReference.getItemResponseBody Body;
        
        public getItemResponse() {
        }
        
        public getItemResponse(Order_Application_Seller.ProductDetailsReference.getItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ProductView.asmx/")]
    public partial class getItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Order_Application_Seller.ProductDetailsReference.Item getItemResult;
        
        public getItemResponseBody() {
        }
        
        public getItemResponseBody(Order_Application_Seller.ProductDetailsReference.Item getItemResult) {
            this.getItemResult = getItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductViewSoapChannel : Order_Application_Seller.ProductDetailsReference.ProductViewSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductViewSoapClient : System.ServiceModel.ClientBase<Order_Application_Seller.ProductDetailsReference.ProductViewSoap>, Order_Application_Seller.ProductDetailsReference.ProductViewSoap {
        
        public ProductViewSoapClient() {
        }
        
        public ProductViewSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductViewSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductViewSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductViewSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Order_Application_Seller.ProductDetailsReference.getItemResponse Order_Application_Seller.ProductDetailsReference.ProductViewSoap.getItem(Order_Application_Seller.ProductDetailsReference.getItemRequest request) {
            return base.Channel.getItem(request);
        }
        
        public Order_Application_Seller.ProductDetailsReference.Item getItem(int id) {
            Order_Application_Seller.ProductDetailsReference.getItemRequest inValue = new Order_Application_Seller.ProductDetailsReference.getItemRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.getItemRequestBody();
            inValue.Body.id = id;
            Order_Application_Seller.ProductDetailsReference.getItemResponse retVal = ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).getItem(inValue);
            return retVal.Body.getItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.getItemResponse> Order_Application_Seller.ProductDetailsReference.ProductViewSoap.getItemAsync(Order_Application_Seller.ProductDetailsReference.getItemRequest request) {
            return base.Channel.getItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Order_Application_Seller.ProductDetailsReference.getItemResponse> getItemAsync(int id) {
            Order_Application_Seller.ProductDetailsReference.getItemRequest inValue = new Order_Application_Seller.ProductDetailsReference.getItemRequest();
            inValue.Body = new Order_Application_Seller.ProductDetailsReference.getItemRequestBody();
            inValue.Body.id = id;
            return ((Order_Application_Seller.ProductDetailsReference.ProductViewSoap)(this)).getItemAsync(inValue);
        }
        
        public int addRating(int id, int rating) {
            return base.Channel.addRating(id, rating);
        }
        
        public System.Threading.Tasks.Task<int> addRatingAsync(int id, int rating) {
            return base.Channel.addRatingAsync(id, rating);
        }
    }
}
