//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Admin.SalesReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/ViewSales.asmx/", ConfigurationName="SalesReference.ViewSalesSoap")]
    public interface ViewSalesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ViewSales.asmx/getSalesData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getSalesData(string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ViewSales.asmx/getSalesData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getSalesDataAsync(string startDate, string endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViewSalesSoapChannel : Order_Application_Admin.SalesReference.ViewSalesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewSalesSoapClient : System.ServiceModel.ClientBase<Order_Application_Admin.SalesReference.ViewSalesSoap>, Order_Application_Admin.SalesReference.ViewSalesSoap {
        
        public ViewSalesSoapClient() {
        }
        
        public ViewSalesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewSalesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewSalesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewSalesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getSalesData(string startDate, string endDate) {
            return base.Channel.getSalesData(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getSalesDataAsync(string startDate, string endDate) {
            return base.Channel.getSalesDataAsync(startDate, endDate);
        }
    }
}
