//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Admin.DashboardReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/DashboardValues.asmx/", ConfigurationName="DashboardReference.DashboardValuesSoap")]
    public interface DashboardValuesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DashboardValues.asmx/GetDashboardData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDashboardData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DashboardValues.asmx/GetDashboardData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDashboardDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DashboardValuesSoapChannel : Order_Application_Admin.DashboardReference.DashboardValuesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DashboardValuesSoapClient : System.ServiceModel.ClientBase<Order_Application_Admin.DashboardReference.DashboardValuesSoap>, Order_Application_Admin.DashboardReference.DashboardValuesSoap {
        
        public DashboardValuesSoapClient() {
        }
        
        public DashboardValuesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DashboardValuesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardValuesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardValuesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDashboardData() {
            return base.Channel.GetDashboardData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDashboardDataAsync() {
            return base.Channel.GetDashboardDataAsync();
        }
    }
}
