//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Admin.SubcategoryReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/Subcategories.asmx/", ConfigurationName="SubcategoryReference.SubcategoriesSoap")]
    public interface SubcategoriesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/getCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/getCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/getSubcategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getSubcategories(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/getSubcategories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getSubcategoriesAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/subCategoryExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int subCategoryExists(string subcategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/subCategoryExists", ReplyAction="*")]
        System.Threading.Tasks.Task<int> subCategoryExistsAsync(string subcategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/addSubCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int addSubCategory(string subcategory, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Subcategories.asmx/addSubCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addSubCategoryAsync(string subcategory, string category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubcategoriesSoapChannel : Order_Application_Admin.SubcategoryReference.SubcategoriesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubcategoriesSoapClient : System.ServiceModel.ClientBase<Order_Application_Admin.SubcategoryReference.SubcategoriesSoap>, Order_Application_Admin.SubcategoryReference.SubcategoriesSoap {
        
        public SubcategoriesSoapClient() {
        }
        
        public SubcategoriesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubcategoriesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubcategoriesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubcategoriesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getCategories() {
            return base.Channel.getCategories();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getCategoriesAsync() {
            return base.Channel.getCategoriesAsync();
        }
        
        public System.Data.DataTable getSubcategories(string category) {
            return base.Channel.getSubcategories(category);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getSubcategoriesAsync(string category) {
            return base.Channel.getSubcategoriesAsync(category);
        }
        
        public int subCategoryExists(string subcategory) {
            return base.Channel.subCategoryExists(subcategory);
        }
        
        public System.Threading.Tasks.Task<int> subCategoryExistsAsync(string subcategory) {
            return base.Channel.subCategoryExistsAsync(subcategory);
        }
        
        public int addSubCategory(string subcategory, string category) {
            return base.Channel.addSubCategory(subcategory, category);
        }
        
        public System.Threading.Tasks.Task<int> addSubCategoryAsync(string subcategory, string category) {
            return base.Channel.addSubCategoryAsync(subcategory, category);
        }
    }
}
