//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Seller.ViewProductReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_pathField;
        
        private double discountField;
        
        private double ratingField;
        
        private int ratingCountField;
        
        private int order_countField;
        
        private int quantity_availableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subcategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string image_path {
            get {
                return this.image_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.image_pathField, value) != true)) {
                    this.image_pathField = value;
                    this.RaisePropertyChanged("image_path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ratingCount {
            get {
                return this.ratingCountField;
            }
            set {
                if ((this.ratingCountField.Equals(value) != true)) {
                    this.ratingCountField = value;
                    this.RaisePropertyChanged("ratingCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int order_count {
            get {
                return this.order_countField;
            }
            set {
                if ((this.order_countField.Equals(value) != true)) {
                    this.order_countField = value;
                    this.RaisePropertyChanged("order_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int quantity_available {
            get {
                return this.quantity_availableField;
            }
            set {
                if ((this.quantity_availableField.Equals(value) != true)) {
                    this.quantity_availableField = value;
                    this.RaisePropertyChanged("quantity_available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string subcategory {
            get {
                return this.subcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.subcategoryField, value) != true)) {
                    this.subcategoryField = value;
                    this.RaisePropertyChanged("subcategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/", ConfigurationName="ViewProductReference.ViewItemsSoap")]
    public interface ViewItemsSoap {
        
        // CODEGEN: Generating message contract since element name itemsResult from namespace http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/items", ReplyAction="*")]
        Order_Application_Seller.ViewProductReference.itemsResponse items(Order_Application_Seller.ViewProductReference.itemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/items", ReplyAction="*")]
        System.Threading.Tasks.Task<Order_Application_Seller.ViewProductReference.itemsResponse> itemsAsync(Order_Application_Seller.ViewProductReference.itemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/itemCount", ReplyAction="*")]
        int itemCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/itemCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> itemCountAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class itemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="items", Namespace="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/", Order=0)]
        public Order_Application_Seller.ViewProductReference.itemsRequestBody Body;
        
        public itemsRequest() {
        }
        
        public itemsRequest(Order_Application_Seller.ViewProductReference.itemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/")]
    public partial class itemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int page;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int filter;
        
        public itemsRequestBody() {
        }
        
        public itemsRequestBody(int page, int filter) {
            this.page = page;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class itemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="itemsResponse", Namespace="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/", Order=0)]
        public Order_Application_Seller.ViewProductReference.itemsResponseBody Body;
        
        public itemsResponse() {
        }
        
        public itemsResponse(Order_Application_Seller.ViewProductReference.itemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/ViewItems.asmx/")]
    public partial class itemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Order_Application_Seller.ViewProductReference.Item[] itemsResult;
        
        public itemsResponseBody() {
        }
        
        public itemsResponseBody(Order_Application_Seller.ViewProductReference.Item[] itemsResult) {
            this.itemsResult = itemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViewItemsSoapChannel : Order_Application_Seller.ViewProductReference.ViewItemsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewItemsSoapClient : System.ServiceModel.ClientBase<Order_Application_Seller.ViewProductReference.ViewItemsSoap>, Order_Application_Seller.ViewProductReference.ViewItemsSoap {
        
        public ViewItemsSoapClient() {
        }
        
        public ViewItemsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewItemsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewItemsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewItemsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Order_Application_Seller.ViewProductReference.itemsResponse Order_Application_Seller.ViewProductReference.ViewItemsSoap.items(Order_Application_Seller.ViewProductReference.itemsRequest request) {
            return base.Channel.items(request);
        }
        
        public Order_Application_Seller.ViewProductReference.Item[] items(int page, int filter) {
            Order_Application_Seller.ViewProductReference.itemsRequest inValue = new Order_Application_Seller.ViewProductReference.itemsRequest();
            inValue.Body = new Order_Application_Seller.ViewProductReference.itemsRequestBody();
            inValue.Body.page = page;
            inValue.Body.filter = filter;
            Order_Application_Seller.ViewProductReference.itemsResponse retVal = ((Order_Application_Seller.ViewProductReference.ViewItemsSoap)(this)).items(inValue);
            return retVal.Body.itemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Order_Application_Seller.ViewProductReference.itemsResponse> Order_Application_Seller.ViewProductReference.ViewItemsSoap.itemsAsync(Order_Application_Seller.ViewProductReference.itemsRequest request) {
            return base.Channel.itemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Order_Application_Seller.ViewProductReference.itemsResponse> itemsAsync(int page, int filter) {
            Order_Application_Seller.ViewProductReference.itemsRequest inValue = new Order_Application_Seller.ViewProductReference.itemsRequest();
            inValue.Body = new Order_Application_Seller.ViewProductReference.itemsRequestBody();
            inValue.Body.page = page;
            inValue.Body.filter = filter;
            return ((Order_Application_Seller.ViewProductReference.ViewItemsSoap)(this)).itemsAsync(inValue);
        }
        
        public int itemCount() {
            return base.Channel.itemCount();
        }
        
        public System.Threading.Tasks.Task<int> itemCountAsync() {
            return base.Channel.itemCountAsync();
        }
    }
}
