//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Seller.ReviewsReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx", ConfigurationName="ReviewsReference.ReviewsSoap")]
    public interface ReviewsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/GetTopReviews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Order_Application_Seller.ReviewsReference.Review[] GetTopReviews(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/GetTopReviews", ReplyAction="*")]
        System.Threading.Tasks.Task<Order_Application_Seller.ReviewsReference.Review[]> GetTopReviewsAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/GetSubReviews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Order_Application_Seller.ReviewsReference.Review[] GetSubReviews(int productID, int reviewID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/GetSubReviews", ReplyAction="*")]
        System.Threading.Tasks.Task<Order_Application_Seller.ReviewsReference.Review[]> GetSubReviewsAsync(int productID, int reviewID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/addReview", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int addReview(int itemID, int originalID, string username, string review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/addReview", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addReviewAsync(int itemID, int originalID, string username, string review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/getUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx/getUser", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getUserAsync(string username);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/ServiceApplicationBuyGrandSeller/Review.asmx")]
    public partial class Review : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int reviewIDField;
        
        private int subReviewCountField;
        
        private string imagePathField;
        
        private string nameField;
        
        private string datetimeField;
        
        private string reviewDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int reviewID {
            get {
                return this.reviewIDField;
            }
            set {
                this.reviewIDField = value;
                this.RaisePropertyChanged("reviewID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int subReviewCount {
            get {
                return this.subReviewCountField;
            }
            set {
                this.subReviewCountField = value;
                this.RaisePropertyChanged("subReviewCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string imagePath {
            get {
                return this.imagePathField;
            }
            set {
                this.imagePathField = value;
                this.RaisePropertyChanged("imagePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
                this.RaisePropertyChanged("datetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string reviewDesc {
            get {
                return this.reviewDescField;
            }
            set {
                this.reviewDescField = value;
                this.RaisePropertyChanged("reviewDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReviewsSoapChannel : Order_Application_Seller.ReviewsReference.ReviewsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReviewsSoapClient : System.ServiceModel.ClientBase<Order_Application_Seller.ReviewsReference.ReviewsSoap>, Order_Application_Seller.ReviewsReference.ReviewsSoap {
        
        public ReviewsSoapClient() {
        }
        
        public ReviewsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReviewsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Order_Application_Seller.ReviewsReference.Review[] GetTopReviews(int productID) {
            return base.Channel.GetTopReviews(productID);
        }
        
        public System.Threading.Tasks.Task<Order_Application_Seller.ReviewsReference.Review[]> GetTopReviewsAsync(int productID) {
            return base.Channel.GetTopReviewsAsync(productID);
        }
        
        public Order_Application_Seller.ReviewsReference.Review[] GetSubReviews(int productID, int reviewID) {
            return base.Channel.GetSubReviews(productID, reviewID);
        }
        
        public System.Threading.Tasks.Task<Order_Application_Seller.ReviewsReference.Review[]> GetSubReviewsAsync(int productID, int reviewID) {
            return base.Channel.GetSubReviewsAsync(productID, reviewID);
        }
        
        public int addReview(int itemID, int originalID, string username, string review) {
            return base.Channel.addReview(itemID, originalID, username, review);
        }
        
        public System.Threading.Tasks.Task<int> addReviewAsync(int itemID, int originalID, string username, string review) {
            return base.Channel.addReviewAsync(itemID, originalID, username, review);
        }
        
        public System.Data.DataTable getUser(string username) {
            return base.Channel.getUser(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getUserAsync(string username) {
            return base.Channel.getUserAsync(username);
        }
    }
}
