//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Admin.CategoryReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/category.asmx/", ConfigurationName="CategoryReference.CategorySoap")]
    public interface CategorySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/categories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable categories(int startIndex, int endIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/categories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> categoriesAsync(int startIndex, int endIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string add(string category, string subcategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/add", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addAsync(string category, string subcategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/updateCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string updateCategory(string categoryUpdated, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/updateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> updateCategoryAsync(string categoryUpdated, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/deleteCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string deleteCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/deleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> deleteCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/getSubcategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getSubcategories(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/getSubcategories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getSubcategoriesAsync(string category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategorySoapChannel : Order_Application_Admin.CategoryReference.CategorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategorySoapClient : System.ServiceModel.ClientBase<Order_Application_Admin.CategoryReference.CategorySoap>, Order_Application_Admin.CategoryReference.CategorySoap {
        
        public CategorySoapClient() {
        }
        
        public CategorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable categories(int startIndex, int endIndex) {
            return base.Channel.categories(startIndex, endIndex);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> categoriesAsync(int startIndex, int endIndex) {
            return base.Channel.categoriesAsync(startIndex, endIndex);
        }
        
        public string add(string category, string subcategory) {
            return base.Channel.add(category, subcategory);
        }
        
        public System.Threading.Tasks.Task<string> addAsync(string category, string subcategory) {
            return base.Channel.addAsync(category, subcategory);
        }
        
        public string updateCategory(string categoryUpdated, string category) {
            return base.Channel.updateCategory(categoryUpdated, category);
        }
        
        public System.Threading.Tasks.Task<string> updateCategoryAsync(string categoryUpdated, string category) {
            return base.Channel.updateCategoryAsync(categoryUpdated, category);
        }
        
        public string deleteCategory(string category) {
            return base.Channel.deleteCategory(category);
        }
        
        public System.Threading.Tasks.Task<string> deleteCategoryAsync(string category) {
            return base.Channel.deleteCategoryAsync(category);
        }
        
        public System.Data.DataTable getSubcategories(string category) {
            return base.Channel.getSubcategories(category);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getSubcategoriesAsync(string category) {
            return base.Channel.getSubcategoriesAsync(category);
        }
    }
}
