//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Admin.CategoryReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/category.asmx/", ConfigurationName="CategoryReference.CategorySoap")]
    public interface CategorySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/categories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable categories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/category.asmx/categories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> categoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategorySoapChannel : Order_Application_Admin.CategoryReference.CategorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategorySoapClient : System.ServiceModel.ClientBase<Order_Application_Admin.CategoryReference.CategorySoap>, Order_Application_Admin.CategoryReference.CategorySoap {
        
        public CategorySoapClient() {
        }
        
        public CategorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable categories() {
            return base.Channel.categories();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> categoriesAsync() {
            return base.Channel.categoriesAsync();
        }
    }
}
