//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Application_Seller.SalesReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/ServiceBuyGrandSeller/SalesDetails.asmx/", ConfigurationName="SalesReference.SalesDetailsSoap")]
    public interface SalesDetailsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/SalesDetails.asmx/Sales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Sales(string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ServiceBuyGrandSeller/SalesDetails.asmx/Sales", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SalesAsync(string startDate, string endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesDetailsSoapChannel : Order_Application_Seller.SalesReference.SalesDetailsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesDetailsSoapClient : System.ServiceModel.ClientBase<Order_Application_Seller.SalesReference.SalesDetailsSoap>, Order_Application_Seller.SalesReference.SalesDetailsSoap {
        
        public SalesDetailsSoapClient() {
        }
        
        public SalesDetailsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesDetailsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDetailsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDetailsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Sales(string startDate, string endDate) {
            return base.Channel.Sales(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SalesAsync(string startDate, string endDate) {
            return base.Channel.SalesAsync(startDate, endDate);
        }
    }
}
